kind: Service
apiVersion: v1
metadata:
  name: ubuntu-desktop
#  namespace: zhanghong
spec:
  selector:
    app: ubuntu-desktop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: TCP
    port: 5900
    targetPort: 5900
    name: vnc    
