kind: ConfigMap
metadata:
  name: profile-config
#  namespace: iotbull
apiVersion: v1
data:
  .bashrc: |-
    [ -z "$PS1" ] && return
    HISTCONTROL=ignoredups:ignorespace
    shopt -s histappend
    HISTSIZE=1000
    HISTFILESIZE=2000
    shopt -s checkwinsize
    [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
    if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
        debian_chroot=$(cat /etc/debian_chroot)
    fi
    case "$TERM" in
        xterm-color) color_prompt=yes;;
    esac
    
    if [ -n "$force_color_prompt" ]; then
        if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
      # We have color support; assume it's compliant with Ecma-48
      # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
      # a case would tend to support setf rather than setaf.)
      color_prompt=yes
        else
      color_prompt=
        fi
    fi
    
    if [ "$color_prompt" = yes ]; then
        PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    else
        PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
    fi
    unset color_prompt force_color_prompt
    
    # If this is an xterm set the title to user@host:dir
    case "$TERM" in
    xterm*|rxvt*)
        PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
        ;;
    *)
        ;;
    esac
    
    # enable color support of ls and also add handy aliases
    if [ -x /usr/bin/dircolors ]; then
        test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
        alias ls='ls --color=auto'
        #alias dir='dir --color=auto'
        #alias vdir='vdir --color=auto'
    
        alias grep='grep --color=auto'
        alias fgrep='fgrep --color=auto'
        alias egrep='egrep --color=auto'
    fi
    
    # some more ls aliases
    alias ll='ls -alF'
    alias la='ls -A'
    alias l='ls -CF'
    
    # Alias definitions.
    # You may want to put all your additions into a separate file like
    # ~/.bash_aliases, instead of adding them here directly.
    # See /usr/share/doc/bash-doc/examples in the bash-doc package.
    
    if [ -f ~/.bash_aliases ]; then
        . ~/.bash_aliases
    fi
    export JAVA_HOME=/work/java
    export JRE_HOME=/work/java/jre
    export PATH=$JAVA_HOME/bin:$PATH
    export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar

    export M2_HOME=/work/apache-maven-3.5.0
    export PATH=$M2_HOME/bin:$PATH

---

apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-desktop
  namespace: zhanghong
  labels:
    app: ubuntu-desktop
spec:
  restartPolicy: Always   
  nodeName: okd-node-4  
  imagePullSecrets:
  - name: secret-aliyuncs         
  containers:
  - name: ubuntu-desktop
    image:  registry.cn-hangzhou.aliyuncs.com/iotbull/ubuntu-desktop
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 80
    - name: vnc
      containerPort: 5900
    volumeMounts:
    - mountPath: /work/workspace
      name: workspace-volume 
    - mountPath: /root/git
      name: git-volume 
    - mountPath: /root/.m2
      name: m2-volume             
    - name: configmap
      mountPath: /root/.bashrc  
      subPath: path/to/.bashrc   
    securityContext:
      privileged: true
    env:
    - name: VNC_PASSWORD
      value: mypassword
    - name: RESOLUTION
      value: 1920x1080
    resources:
      requests:
        cpu: 2
        memory: 8Gi
      limits:
        memory: 8Gi      
  volumes:
  - name: workspace-volume
    hostPath:
      path: /work/zhanghong/workspace    
  - name: m2-volume
    hostPath:
      path: /work/zhanghong/m2       
  - name: git-volume
    hostPath:
      path: /work/zhanghong/git             
  - name: configmap
    configMap:
      name: profile-config 
      items:
      - key: .bashrc
        path: path/to/.bashrc
          

          